name : CI/CD demo
on:
	push:
		branches: [main]
jobs: 
	build:
		runs-on : ubuntu-latest
		steps:
			- uses: action/checkout@v3
			- name: Setup Node.js
			  uses: action/setup-node@v3
			  with:
				node-version: 18
			-run: npm install
			-run: npm start &
			env:
				PORT:8080
			-run: echo "CI/CD berjalan dengan baik!"
